### ISSUE TITLE
Test conflict between pytest and flask

### ISSUE THREAD

**Issue by bilalshaikh42** [KarrLab/datanator_rest_api#1]
Pytest 5.0.0 (and above?) have a conflict with flask 1.04 and below. Look at the requirements for karr_lab_build_utils and this package to diagnose. 
Perhaps need to explicitly define test requirements to use a different  version of flask or pytest 

https://github.com/pytest-dev/pytest/issues/5532

**Comment by jonrkarr** [comment]
Do you need an old version of flask?

**Comment by bilalshaikh42** [comment]
Apparently, this was already fixed in connexion by upgrading flask >1.04. Tests are passing locally, but not on circleci.  Circle ci is using pytest 5.01 for this build, so flask must be the outdated package

https://github.com/zalando/connexion/issues/991

**Comment by jonrkarr** [comment]
In the requirements, specify the minimum flask version needed. This should
make circle update flask.

**Comment by bilalshaikh42** [comment]
While the current connexion package requires flask > 1.04 it seems that the circle build somehow thinks it only needs >0.10. Adding the explicit requirement does make circle update, but it might be worth looking into why it didn't happen automatically. 
From circle: 
Requirement already satisfied, skipping upgrade: connexion in /usr/local/lib/python3.6/site-packages (from datanator-rest-api==0.0.1) (2.3.0)  #this should require flask>=1.0.4

Requirement already satisfied, skipping upgrade: flask>=0.10.1 in /usr/local/lib/python3.6/site-packages (from connexion->datanator-rest-api==0.0.1) (1.0.2)  #however, pip believes it only needs> 0.10.1 which was changed in the connexion issue refrences above

**Comment by bilalshaikh42** [comment]
While the issue with flask does resolve with the explicit requirement, there are now other collection failures. I'll keep experimenting

**Comment by jonrkarr** [comment]
Could be related to the order of operations. When I've had difficulty with
package versions, I've updated the docker image.

**Comment by bilalshaikh42** [comment]
Adding flask  package version to test requirement file before requirements that use flask a s sub dependency resolved issue.
