### ISSUE TITLE
Add organism name to gene full-text search results for individual genes (e.g., results identified by UniProt ids)

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#100]
This will allow us to display the organism name in the search results. See also KarrLab/datanator_frontend#258.

**Comment by lzy7071** [comment]
http://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=Brain-derived%20neurotrophic%20factor%20%28BDNF%29%20%28Fragment%29&from_=0&size=10&fields=uniprot_id&fields=protein_name now contains `species_name`

**Comment by jonrkarr** [comment]
I don't see `species_name` in the results. Can you double check?

**Comment by lzy7071** [comment]
> I don't see `species_name` in the results. Can you double check?

I had to merge the master branch file to testapi branch and forgot to add the `species_name` back. It is there now. Sorry about that.

**Comment by jonrkarr** [comment]
I integrated this into the frontend
