### ISSUE TITLE
Reactions kinetics endpoint with taxonomic distance calculations is down (500)

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#101]
https://testapi.datanator.info/reactions/kinlaw_by_rxn/?_from=0&size=1000&bound=loose&dof=0&substrates=YSYKRGRSMLTJNL-KFQCIAAJSA-N&products=PSXWNITXWWECNY-UCBTUHGZSA-N,XLYOFNOQVPJJNP-UHFFFAOYSA-N&taxon_distance=true&species=Escherichia%20coli

**Comment by lzy7071** [comment]
Fixed, doesn't return an error now. (`CommandCursor` object, which is the obj returned by `aggregate`, is not JSON serializable.)

**Comment by lzy7071** [comment]
I'm looking into why https://api.datanator.info/reactions/kinlaw_by_rxn/?_from=0&size=10&bound=loose&dof=0&substrates=YSYKRGRSMLTJNL-KFQCIAAJSA-N&products=PSXWNITXWWECNY-UCBTUHGZSA-N,XLYOFNOQVPJJNP-UHFFFAOYSA-N&taxon_distance=true&species=Escherichia%20coli stopped working. Seems related to AWS Elasticsearch Service.
