### ISSUE TITLE
Kinetics endpoint returns no data when species included

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#104]
This shows results
https://testapi.datanator.info/reactions/kinlaw_by_rxn/?_from=0&size=1000&bound=loose&dof=0&substrates=YSYKRGRSMLTJNL-KFQCIAAJSA-N&products=PSXWNITXWWECNY-UCBTUHGZSA-N,XLYOFNOQVPJJNP-UHFFFAOYSA-N

But this does not
https://testapi.datanator.info/reactions/kinlaw_by_rxn/?_from=0&size=1000&bound=loose&dof=0&substrates=YSYKRGRSMLTJNL-KFQCIAAJSA-N&products=PSXWNITXWWECNY-UCBTUHGZSA-N,XLYOFNOQVPJJNP-UHFFFAOYSA-N&taxon_distance=true&species=Escherichia%20coli

**Comment by lzy7071** [comment]
Fixed.
