### ISSUE TITLE
Extend RNA half-life endpoint to genes identified via individual UniProt ids

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#105]
Replaces #85.

Example: 
https://testapi.datanator.info/rna/halflife/get_info_by_ko/?ko_number=Q8C5G2&_from=0&size=1000
should return 1 half-life

**Comment by lzy7071** [comment]
Endpoint https://testapi.datanator.info/rna/halflife/get_info_by_uniprot/?uniprot_id=Q8C5G2&_from=0&size=1000

**Comment by jonrkarr** [comment]
I integrated this into the frontend
