### ISSUE TITLE
Extend protein modifications endpoint to genes identified via individual UniProt ids

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#106]
Replaces #85.

Example:
https://testapi.datanator.info/proteins/precise_abundance/?uniprot_id=P37173
should return 18 modifications

**Comment by lzy7071** [comment]
Done.

**Comment by jonrkarr** [comment]
The results have `NaN`. Can you please replace this with `null`?

**Comment by lzy7071** [comment]
> The results have `NaN`. Can you please replace this with `null`?

Done.

**Comment by jonrkarr** [comment]
I integrated this into the frontend.
