### ISSUE TITLE
Use AWS ECS to scale REST API and move away from Heroku

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_rest_api#107]

**Comment by jonrkarr** [comment]
This seems like a good idea. Is this part of the reason that the REST API fails intermittently?

**Comment by lzy7071** [comment]
I suspect so but I can't be sure.

**Comment by lzy7071** [comment]
Build on Circle -> push to ECR -> deploy to ECS

**Comment by lzy7071** [comment]
Base docker image on tiangolo/meinheld-gunicorn-flask

**Comment by lzy7071** [comment]
Use https://github.com/KarrLab/datanator_rest_api_aws to instantiate an AWS deployment stack.

**Comment by lzy7071** [comment]
Build Docker with secret envs using [BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/)

**Comment by lzy7071** [comment]
`Load Balancer`  in VPC across 1 AZ with 2 security groups, one for public subnet, the other for the containers.

**Comment by lzy7071** [comment]
Need to create log groups in https://github.com/KarrLab/datanator_rest_api_aws/blob/master/ecs_ecr_templates/public-service.yml

**Comment by lzy7071** [comment]
Need to have READ_PREFERENCE env variable.

**Comment by lzy7071** [comment]
Done.
