### ISSUE TITLE
Protein abundance endpoint is not calculating taxonomic distances

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#109]
Example:
https://testapi.datanator.info/proteins/precise_abundance/?uniprot_id=P37173&taxon_distance=true&taget_species=Escherichia%20coli

The endpoint seems to be ignoring the value of `taget_species` and using the value `Homo sapiens`.

This might be related to #108.

**Comment by lzy7071** [comment]
As you suggested, this is indeed a result of https://github.com/KarrLab/datanator_rest_api/issues/108
