### ISSUE TITLE
Kinetics endpoint is failing on the API, but not on the test API

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#111]
Working:
https://testapi.datanator.info/reactions/kinlaw_by_rxn/?_from=0&size=1000&bound=loose&dof=0&substrates=YSYKRGRSMLTJNL-KFQCIAAJSA-N&products=PSXWNITXWWECNY-UCBTUHGZSA-N,XLYOFNOQVPJJNP-UHFFFAOYSA-N&taxon_distance=true&species=Escherichia%20coli

Not working:
https://api.datanator.info/reactions/kinlaw_by_rxn/?_from=0&size=1000&bound=loose&dof=0&substrates=YSYKRGRSMLTJNL-KFQCIAAJSA-N&products=PSXWNITXWWECNY-UCBTUHGZSA-N,XLYOFNOQVPJJNP-UHFFFAOYSA-N&taxon_distance=true&species=Escherichia%20coli

**Comment by jonrkarr** [comment]
These failures seem to be fairly common. If this related to Heroku, then I think we should deal with #107 relatively soon.

**Comment by lzy7071** [comment]
This was not an issue of Heroku. I haven't changed the master branch (datanator_query_python and datanator_rest_api) in a while because I was thinking once we finalized the first test version (test-frontend, test-rest-api, test-datanator-query-python), I would just merge the test branch into master branch.

**Comment by jonrkarr** [comment]
Got it. In that case, I'll start pushing to the dev branch rather than master. Then CircleCI will use the test API.

**Comment by lzy7071** [comment]
> These failures seem to be fairly common. If this related to Heroku, then I think we should deal with #107 relatively soon.

It was a result of changing some of the query functions from `find` in MongoDB to `aggregate` in MongoDB. The two functions return two different types of objects that need to be handled differently.
