### ISSUE TITLE
Protein abundance endpoint sometimes returns errors when there's no relevant data

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#112]
Examples:
- Q6Y9H0
  - Returns no data (without organism): https://testapi.datanator.info/proteins/precise_abundance/?uniprot_id=Q6Y9H0
  - 500 error (with organism): https://testapi.datanator.info/proteins/precise_abundance/?uniprot_id=Q6Y9H0&taxon_distance=true&target_species=Saccharomyces%20cerevisiae
- https://testapi.datanator.info/proteins/precise_abundance/?uniprot_id=A0A1T0AW49&taxon_distance=true&target_species=Saccharomyces%20cerevisiae
- https://testapi.datanator.info/proteins/precise_abundance/?uniprot_id=Q41406&taxon_distance=true&target_species=Saccharomyces%20cerevisiae

**Comment by lzy7071** [comment]
Fixed
