### ISSUE TITLE
Kinetics endpoint fails for some reactions when an organism is included

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#114]
Example
- L-lactate dehydrogenase
  - Succeeds without organism: https://testapi.datanator.info/reactions/kinlaw_by_rxn/?_from=0&size=1000&bound=loose&dof=0&substrates=GPRLSGONYQIRFK-UHFFFAOYSA-N,LCTONWCANYUPML-UHFFFAOYSA-N,BOPGDPNILDQYTO-NNYOXOHSSA-N&products=JVTAAEKCZFNVCJ-REOHCLBHSA-N,BAWFJGJZGIEFAR-NNYOXOHSSA-O
  - Fails with organism: https://testapi.datanator.info/reactions/kinlaw_by_rxn/?_from=0&size=1000&bound=loose&dof=0&substrates=GPRLSGONYQIRFK-UHFFFAOYSA-N,LCTONWCANYUPML-UHFFFAOYSA-N,BOPGDPNILDQYTO-NNYOXOHSSA-N&products=JVTAAEKCZFNVCJ-REOHCLBHSA-N,BAWFJGJZGIEFAR-NNYOXOHSSA-O&taxon_distance=true&species=Saccharomyces%20cerevisiae

**Comment by lzy7071** [comment]
Temporarily fixed. Need to update `sabio_rk` collection to pull in updated taxon information.
