### ISSUE TITLE
Some substrate/products are missing hashes

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#116]
Example -- element 3 of:
https://testapi.datanator.info/ftx/text_search/num_of_index/?query_message=glucose&index=sabio_reaction_entries&from_=0&size=10&fields=enzyme_names&fields=ec-code&fields=substrates&fields=substrate_names&fields=products&fields=product_names

**Comment by lzy7071** [comment]
Need to hash reactants in `sabio_reaction_entries`  collection and sync with the corresponding ES index.

**Comment by lzy7071** [comment]
Done.
