### ISSUE TITLE
"Record request exceeds limit" failures should return a 500 error

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#120]
Example: 
- Query: https://api.datanator.info/kegg/get_meta/?kegg_ids=K223755050
- Response (200): 
  ```
  "Record request exceeds limit"
  ```

The frontend has difficulty handling this because the server doesn't return an error. I think this should be categorized as a 500 error.

**Comment by lzy7071** [comment]
This response is to indicate no records found, because there is no `kegg_id` that equals to `K223755050`. I will change it to return an empty array.

**Comment by lzy7071** [comment]
Done.

**Comment by jonrkarr** [comment]
Thanks! The frontend now displays a 404 message to users.
