### ISSUE TITLE
Some OrthoDB groups are missing names

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#122]
Example: name for 1637267at2759 is missing from the result below

(the entry with `"orthodb_id": "1637267at2759",` has `"orthodb_name": "",`)

https://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=glucose&from_=0&size=50&fields=orthodb_id&fields=orthodb_name&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number

**Comment by lzy7071** [comment]
Filling missing information. Needs to feed docs to elasticsearch engine afterwards.

**Comment by lzy7071** [comment]
> Filling missing information. Needs to feed docs to elasticsearch engine afterwards.

Done

**Comment by jonrkarr** [comment]
Looks good
