### ISSUE TITLE
Add OrthoDB ids for enzymes

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#123]
Previously `reactions/kinlaw_by_rxn/` contained the KO id for each enzyme. We used this to provide links from reaction pages to pages with data about the enzyme. 

This should now return the OrthoDB id for the enzyme

**Comment by lzy7071** [comment]
Previously this was done via an aggregation pipeline. Collections are now in two databases so `lookup` can't be done. Temporarily fixed. Should add orthodb info to `sabio_rk` collection.

**Comment by jonrkarr** [comment]
This is less important to fix now. For now, this is basically commented out in the frontend.

**Comment by lzy7071** [comment]
Opened issue in `datanator` repo.
