### ISSUE TITLE
How can I retrieve reactions associated with an OrthoDB group?

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#124]
Is the URL below the intended pattern? Can you point me to an example so I can make sure the frontend is updated correctly?

`proteins/related/related_reactions_by_kegg/?ko=567019at2`

**Comment by lzy7071** [comment]
Yes. This should be fixed in five minutes.

**Comment by lzy7071** [comment]
https://github.com/KarrLab/datanator_query_python/commit/4a92df37467a5764213fa36162e327ef7e65b6d8 fixed the issue.

**Comment by jonrkarr** [comment]
Can you point me to an example URL which returns data so I can make sure the frontend is updated correctly?

**Comment by lzy7071** [comment]
> Can you point me to an example URL which returns data so I can make sure the frontend is updated correctly?

Sorry for the delay. I was fixing other issues. It seems circle downstream trigger only tests for master branch so the `testapi` branch of `datanator_rest_api` wasn't tested and deployed. I just manually triggered the tests.

**Comment by jonrkarr** [comment]
Yes, the downstream tests are only setup to trigger tests on the master branch of the downstream package.

**Comment by lzy7071** [comment]
This is working now https://testapi.datanator.info/proteins/related/related_reactions_by_kegg/?ko=643917at2
The reason `567019at2` didn't return any results is that we have two entries of proteins that fall under `567019at2`: `P07999` and `P13650`, neither of which catalyzes or is a part of an enzyme that catalyzes reactions recorded in SABIO-RK.

**Comment by jonrkarr** [comment]
Looks good. 

Yes, I know not all genes catalyze reactions. Thanks for pointing to an example.
