### ISSUE TITLE
Protein metadata fails for individual UniProt ids

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#128]
Example:
https://testapi.datanator.info/proteins/meta/meta_combo/?uniprot_id=P53984

**Comment by jonrkarr** [comment]
Example of the flow to this endpoint

Search for "adenosine": http://localhost:3000/search/adenosine/

Click on result for "P53984": http://localhost:3000/gene/P53984/

**Comment by lzy7071** [comment]
https://testapi.datanator.info/proteins/meta/meta_combo/?uniprot_id=P53984 is working now.

**Comment by lzy7071** [comment]
Fixed.

**Comment by jonrkarr** [comment]
Thanks!
