### ISSUE TITLE
Gene search results should be grouped by OrthoDB id

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#129]
In the example below, "P00367" appears as a result twice. "P00367" should only appear as a member of an OrthoDB group, and not appear as a separate result just for this UniProt id. I could filter this in the frontend, but this would result in cases where only 9 search results appear instead of the expected 10.
- Individually (second hit)
  - hit to the protein collection
- As a member of the OrthoDB group 692851at2759 (first hit) 
  - hit to the RNA half-life collection

https://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=P00367&from_=0&size=10&fields=orthodb_id&fields=orthodb_name&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number

I can't tell exactly what the issue is. Some possibilities
- The RNA half-life collection is not organized by OrthoDB group
- The search results are not aggregated across the protein, RNA half-live, and other gene collections

**Comment by jonrkarr** [comment]
The other open issues are more important to address than this one

**Comment by lzy7071** [comment]
Feed new docs in `rna_halflife` collection with `orthodb_id` and `orthodb_name` to Elasticsearch.

**Comment by jonrkarr** [comment]
This sounds like a note for you to help you keep track of your work. If this is intended for me, I'm not sure how to follow your notes to revise the frontend.

**Comment by lzy7071** [comment]
> This sounds like a note for you to help you keep track of your work. If this is intended for me, I'm not sure how to follow your notes to revise the frontend.

It's for myself.

**Comment by lzy7071** [comment]
https://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=P00367&from_=0&size=10&fields=orthodb_id&fields=orthodb_name&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number is fixed.

**Comment by jonrkarr** [comment]
Thanks!
