### ISSUE TITLE
API not returning modifications for rRNA

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#131]
I want to make sure that data is properly being displayed about rRNA and tRNA.

I've verified that tRNA work (e.g., tRNA-Ala or tRNA-Arg). Example: http://localhost:3000/gene/tRNA-Ala/Escherichia%20coli/

I want to verify rRNA as well. Example: 
- Frontend: http://localhost:3000/gene/LSU4.5S/
- API endpoint: https://testapi.datanator.info/rna/modification/get_modifications_by_ko/?ko_number=LSU4.5S&_from=0&size=10&taxon_distance=true&target_organism=Escherichia%20coli

However, the API endpoint doesn't return any data. Can you check this?

**Comment by lzy7071** [comment]
See https://github.com/KarrLab/datanator_rest_api/issues/130#issuecomment-706396923

**Comment by lzy7071** [comment]
Fixed.

**Comment by jonrkarr** [comment]
Looks good!
