### ISSUE TITLE
Enable CORS for /metabolites/meta/

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#132]
Example:
https://testapi.datanator.info/metabolites/meta/?inchikey=RFSUNEUAIZKAJO-ARQDHWQXSA-N

**Comment by lzy7071** [comment]
Can you point me to a front end link where this error shows? The API itself seems to work fine. I also tried the production frontend (e.g. https://datanator.info/metabolite/HSCJRCZFDFQWRP-RDKQLNKOSA-N/Escherichia%20coli%20E1002/) and I couldn't find such an error. Sometimes the CORS error came about when there is an additional `/` in the URL and the browser tries to fix the link by redirecting. In any case, CORS has been enabled for a while.

**Comment by jonrkarr** [comment]
This affects the metabolite data pages in testing (localhost:3000 accessing the test api). 

This doesn't impact the deployed version

**Comment by lzy7071** [comment]
CORS is currently working on my end (localhost:3000).

**Comment by jonrkarr** [comment]
It works fine on my machine now.
