### ISSUE TITLE
Bug with taxonomic distance calculation in /proteins/proximity_abundance

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#133]
Examples:
- https://testapi.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=997616at2&distance=40&anchor=Bacillus%20subtilis%20subsp.%20subtilis
- https://testapi.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=1555708at2&distance=40&anchor=Bacillus%20subtilis%20subsp.%20subtilis

**Comment by jonrkarr** [comment]
The error appears to be with the taxonomic distance calculation because the query succeeds without the species. Example:
https://testapi.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=997616at2&distance=40

**Comment by lzy7071** [comment]
Cases where two different species have the same canonical common ancestors were not properly accounted for. It has now been fixed.

Note: having the keyword `fixed` in commit message in front of the issue link seems to automatically close the referenced issue.

**Comment by jonrkarr** [comment]
This looks to be fixed in the API, but the test API still has the error.

I learned about these shortcuts from Bilal. He's been using them. This works in comments on pull requests too. GitHub recognizes several keywords. See https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.

**Comment by lzy7071** [comment]
> This looks to be fixed in the API, but the test API still has the error.

I didn't deploy the test API. Should be fixed once the deployment is done. 
I also found out a big part of the performance issue for this endpoint is due to MongoDB's handling of sparse compound indexes. I've trying different combinations to see if performance can be improved.

**Comment by jonrkarr** [comment]
Improvement to the performance would be great

**Comment by lzy7071** [comment]
Original issue is working now. Moved performance improvement issue to other repo.
