### ISSUE TITLE
Metabolite meta endpoints no longer return data

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#134]
Example: https://api.datanator.info/metabolites/meta/?inchikey=OIRDTQYFTABQOQ-KQYNXXCUSA-N

@lzy7071 could you rollback the database and api to an earlier working version (e.g., around October 12)?

**Comment by lzy7071** [comment]
Yes I'll get this fixed today.

**Comment by lzy7071** [comment]
Two collections need rebuilding (currently being done)

**Comment by lzy7071** [comment]
Collections built near completion. This particular link should be working already.

**Comment by lzy7071** [comment]
This is now fixed.

**Comment by jonrkarr** [comment]
Thanks!
