### ISSUE TITLE
The full text search results for reactions don't seem to be paging

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#14]
All pages seem to return the same data, unlike metabolites and proteins

For example see https://datanator.info/search/?q=glucose&organism=Escherichia%20coli

**Comment by lzy7071** [comment]
Used [bucket_sort](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-pipeline-bucket-sort-aggregation.html) to partially resolve the issue
