### ISSUE TITLE
Add EC numbers to reaction full text search results

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#16]

**Comment by lzy7071** [comment]
EC number can be found in the second object in "resource" from each returned doc, exception being approximately 6% documents don't have an EC number. The object is as follows: {'namespace': 'ec-code', 'id': x.x.x.x}, where x.x.x.x is the EC number.

**Comment by jonrkarr** [comment]
Where is that information located? I don't see `resource` in the result at the URL below.

https://api.datanator.info/ftx/text_search/num_of_index/?query_message=glucose&index=sabio_reaction_entries&from_=0&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzyme_name&fields=product_names&fields=substrate_names&fields=enzymes.subunit.canonical_sequence&fields=species

**Comment by lzy7071** [comment]
Sorry I was thinking of a different index. "sabio_reaction_entries" does not have ES information. I'll add that information.

**Comment by lzy7071** [comment]
The "sabio_reaction_entries" index has been rebuilt. The EC information can be found under "ec-code."
