### ISSUE TITLE
In reactions FTX, the API should only return reactions where there is at either a kcat or km measurement

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#18]
Some reactions that are returned have some kinetic data (e.g. kb, kd), but lack both a kcat and km. Since these (kcat and km) are the only kinetic constants we are currently displaying, we should consider excluding these reactions from the FTX. 

For example:
lets say we look up: Trinitrophenyl-ATP + Diphosphomevalonate decarboxylase → Trinitrophenyl-ATP-Diphosphomevalonate decarboxylase complex

This is sabio reaction id 6716 - http://sabiork.h-its.org/newSearch/index?q=SabioReactionID:%226716%22

This has some data, but does not have any kcat or km measurements. Therefore it will not display any data on the Datanator frontend. Currently this is getting returned in the FTX - https://api.datanator.info/ftx/text_search/num_of_index/?query_message=atp&index=sabio_reaction_entries&from_=0&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzyme_name&fields=product_names&fields=substrate_names&fields=enzymes.subunit.canonical_sequence&fields=species

Is there a way for the FTX to only return reactions that have at least one km or kcat measurement?

**Comment by lzy7071** [comment]
"sabio_reaction_entries" index only returns the user with an aggregate list of rax_id objects. Its primary function is to help form the reaction string (A + B -> C + D) and find all the kinetic law IDs under said reaction. Within each "rxn_id" object, there is a list named "kinlaw_id." "sabio_reaction_entries" index does not contain detailed information about each "kinlaw_id." To check the details of each kinlaw_id for the category-specific display, one has to use calls under reactions/

**Comment by lzy7071** [comment]
There is now a list called "has_poi." The kinlaw_ids in that list all have at least one km or kcat.
