### ISSUE TITLE
Enable protein abundance search without organism

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#20]
For example:
https://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K03841&distance=40&depth=40

**Comment by lzy7071** [comment]
I added a default anchor organism to make the call work. But searching without an anchor organism doesn't make much sense as there will be no starting point on the taxon tree.

**Comment by jonrkarr** [comment]
I know it doesn't make a lot of sense, but the pages should work -- at least minimally -- without typing in an organism. This is useful for exploring the dataset.

**Comment by jonrkarr** [comment]
Does the API need to be re-deployed? I see the error below.

https://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K00973&distance=40&depth=40

```
{
  "detail": "Missing query parameter 'anchor'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

**Comment by lzy7071** [comment]
Fixed.
