### ISSUE TITLE
Customize head banner on api.datanator.info

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_rest_api#22]
1. Replace logo. 
2. Hide search bar.
3. Color adjustment.

**Comment by jonrkarr** [comment]
How do you want to implement this? We could probably replace the style sheet or inject another style sheet.

**Comment by lzy7071** [comment]
Instead of installing "swagger_ui_bundle" as a PyPI package, I'll fork the package, and edit the [UI elements](https://github.com/activelamp/swagger-ui-bundle/tree/master/Resources/public) directly, such as replacing the style sheet as mentioned.

**Comment by jonrkarr** [comment]
Files that need to be replaced are from https://github.com/dtkav/swagger_ui_bundle/tree/master/swagger_ui_bundle/vendor/swagger-ui-3.24.2

- `favicon-16x16.png`
- `favicon-32x32.png`
- `swagger-ui.css` (minified version of `swagger-ui.css.map`)
- `swagger-ui.css.map`
- logo, which must be embedded in one of the `.js` files

**Comment by jonrkarr** [comment]
1. Created fork of `swagger_ui_bundle` -- `datanator_swagger_ui_bundle`
2. Customized "skin" of `datanator_swagger_ui_bundle`
    - Edited/Added metadata to `index.html`
    - Added stylesheet with Datanator styles. Added link to this to `index.html`
    - Edited `swagger-ui-standalone-preset.js` to use Datanator icon and to insert title and subtitle into topbar.
    - Added Datantor logo
    - Overwrote favicon with Datanator favicon

**Comment by jonrkarr** [comment]
I believe this is done. @lzy7071, close the issue once you've verified this is working in the deployed version.

**Comment by lzy7071** [comment]
Deployed. Thank you!

**Comment by jonrkarr** [comment]
I purged the Heroku cache and re-deployed master because the Datanator logo wasn't loading. I think its good now.
