### ISSUE TITLE
Fix metabolite search

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#24]
Queries such as below are no longer working as of a few hours ago

https://api.datanator.info/ftx/text_search/num_of_index/?query_message=glucose&index=metabolites_meta&from_=0&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzyme_name&fields=product_names&fields=substrate_names&fields=enzymes.subunit.canonical_sequence&fields=species

**Comment by lzy7071** [comment]
Done.
