### ISSUE TITLE
Add ChEBI, KEGG, PubChem ids to metabolite search results

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#25]
Add info to this endpoint so we can display more standard ids in search results

https://api.datanator.info/ftx/text_search/num_of_index/?query_message=glucose&index=metabolites_meta&from_=0&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzyme_name&fields=product_names&fields=substrate_names&fields=enzymes.subunit.canonical_sequence&fields=species

**Comment by lzy7071** [comment]
Will incorporate information into corresponding database and index.
1. [libChEBI](https://github.com/libChEBI/libChEBIpy) for ChEBI lookup.
2. [pubchem idex](https://pubchem.ncbi.nlm.nih.gov/idexchange/idexchange.cgi) for pubchem lookup
3. Need to build kegg compound database using [json](https://www.genome.jp/kegg-bin/download_htext?htext=br08001.keg&format=json&filedir=) as a starting point.

**Comment by lzy7071** [comment]
Information contained in source DBs. Add necessary info to meta collection and index.

**Comment by lzy7071** [comment]
Done.
