### ISSUE TITLE
Thoughts on `/datanator/` endpoint

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#30]
- It could be useful to return some version information
  - Version of datanator or datanator rest api
  - Supported version of OpenAPI spec (e.g, 3.0)
- It could be useful to return help and contact info, e.g.
   ``{ ....
     help: "See https://datanator.info/help"
     about: "See https://datanator.info/about"
     contact: "Karr Lab: info@karrlab.org"
      ...}
- Does it make sense to rename the endpoint to something like `/status/` or `/info/`?

**Comment by lzy7071** [comment]
- I'll add version information for each collection into the corresponding documents for datanator.
- REST version information will be included directly in the spec sheet. 
- I can make an endpoint `/status/` where it shows the up/down status of the api. 
- `datanator.info/info` seems a bit redundant to me.

**Comment by jonrkarr** [comment]
To clarify, I was suggesting renaming the endpoint not creating additional endpoints.

**Comment by lzy7071** [comment]
- I renamed [/datanator](https://api.datanator.info/datanator/) to [/status](https://api.datanator.info/status/)
- REST Api version and supported OpenAPI spec are in the `version` and `description` section of the `info` object within the spec sheet. 
- Contact is in the `contact` object

**Comment by jonrkarr** [comment]
Great. I agree there's no need to duplicate information that's contained in the spec. I wasn't aware of that.

FYI, the `/status/` endpoint doesn't display in the documentation for the REST API.

**Comment by lzy7071** [comment]
`/status` is on [api.datanator.info](https://api.datanator.info) But since it is under the tag of "info", one has to scroll down to almost the end of the page to see it.

**Comment by jonrkarr** [comment]
I see.

I guess the first group of endpoints `Datanator` can be removed then. I was confused because the `datanator` endpoint which you renamed was there.

**Comment by lzy7071** [comment]
I just tagged `/status` under both `Datantor` and `Info`.

**Comment by jonrkarr** [comment]
Great. 

I think we can close this.
