### ISSUE TITLE
Return more reaction metadata to populate reaction data page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#33]
Return more metadata from this endpoint:
https://api.datanator.info/reactions/kinlaw_by_name/?substrates=Glucose&products=Glucose&_from=0&size=1000&bound=tight

Metadata we could potentially integrate
- Name
- Alternative name
- Systematic name
- Cofactors
- Pathways
- ~~Comments~~ (Appears to typically be redundant with cofactors)

Potential places to get metadata for each EC number. We only need to use one source. In order of decreasing amount of metadata:
- KEGG: also has pathway information
- https://www.enzyme-database.org/downloads.php
- https://enzyme.expasy.org/, ftp://ftp.expasy.org/databases/enzyme (but doesn't have "systematic name")

**Comment by lzy7071** [comment]
reaction documents now contain a field called `ec_meta` If an EC number has cofactor information, there will be a field called `cofactor` contained in the `ec_meta` object.

**Comment by lzy7071** [comment]
reaction document now may contain a field named `kegg_meta` (depending on if an enzyme subunit has corresponding kegg info or not).

**Comment by yosefdroth** [comment]
Thanks! Does it currently return pathway information? If not, can we include that?

**Comment by lzy7071** [comment]
> Thanks! Does it currently return pathway information? If not, can we include that?

it's in kegg_meta

**Comment by yosefdroth** [comment]
Hi! Do you have any examples of reactions with cofactors? I was not able to find any

**Comment by lzy7071** [comment]
> Hi! Do you have any examples of reactions with cofactors? I was not able to find any

Reaction with kinlaw_id [44](http://api.datanator.info/reactions/kinlaw_doc/?kinlaw_id=44&_from=0&size=10)

**Comment by yosefdroth** [comment]
The way frontend is queried is by searching based on the substrates and products (as opposed by by kinlaw_id). I searched with the substrates and products from that reaction id, but nothing came up. Any idea why? 

Here is the link:
https://api.datanator.info/reactions/kinlaw_by_name/?substrates=S-Adenosyl-L-methionine,8-Amino-7-oxononanoate&products=7,8-Diaminononanoate,S-Adenosyl-4-methylthio-2-oxobutanoatehttps://api.datanator.info/reactions/kinlaw_by_name/?substrates=8-Amino-7-oxononanoate,S-Adenosylmethioninamine&products=S-Adenosyl-3-methylthiopropanal,7,8-Diaminononanoate&_from=0&size=10&bound=tight

**Comment by lzy7071** [comment]
> The way frontend is queried is by searching based on the substrates and products (as opposed by by kinlaw_id). I searched with the substrates and products from that reaction id, but nothing came up. Any idea why?
> 
> Here is the link:
> https://api.datanator.info/reactions/kinlaw_by_name/?substrates=S-Adenosyl-L-methionine,8-Amino-7-oxononanoate&products=7,8-Diaminononanoate,S-Adenosyl-4-methylthio-2-oxobutanoatehttps://api.datanator.info/reactions/kinlaw_by_name/?substrates=8-Amino-7-oxononanoate,S-Adenosylmethioninamine&products=S-Adenosyl-3-methylthiopropanal,7,8-Diaminononanoate&_from=0&size=10&bound=tight

Yeah, you were searching for the names contained within `ec_meta`, which was parsed from [https://www.expasy.org/](ExPASy) The endpoint [/kinlaw_by_name](http://api.datanator.info/reactions/kinlaw_by_name/?substrates=S-Adenosyl-L-methionine&substrates=&products=7%2C8-Diaminononanoate&products=S-Adenosyl-4-methylthio-2-oxobutanoate&_from=0&size=10&bound=loose&taxon_distance=true&species=homo%20sapiens) queries names given by [sabio-rk](http://sabiork.h-its.org/reacdetails.jsp?reactid=3057)

**Comment by yosefdroth** [comment]
Do you know of any examples of cofactors that can be searched with substrate and product names? I would like to add cofactors to the webpage, but I cant find an example I can test it on.

**Comment by yosefdroth** [comment]
thanks! this works
