### ISSUE TITLE
Incorporate additional metadata to display on protein data page into REST API

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#34]
Endpoint to add metadata to: https://api.datanator.info/proteins/meta/meta_combo/?uniprot_id=P39629&uniprot_id=Q9CJ12&uniprot_id=P9WH13&uniprot_id=P61887&uniprot_id=P37744&uniprot_id=P26393&

Metadata
- Name
- List of KEGG pathways

This information is available from KEGG. See example: https://www.genome.jp/dbget-bin/www_bget?ko:K00973

**Comment by lzy7071** [comment]
KEGG meta information can be acquired using [/kegg/get_meta/?kegg_ids={}](https://api.datanator.info/kegg/get_meta/?kegg_ids=K12345&_from=0&size=10)

**Comment by lzy7071** [comment]
There is now a field named "kegg_meta" containing all the available ortholog information for each subdocument.

**Comment by yosefdroth** [comment]
Would we be able to include information about related reactions? For example, if I looked up the protein for phosphofructokinase (K00850), could it list all the reactions that the protein catalyzes? This would be used for the "related links" part of the metadata

**Comment by lzy7071** [comment]
> Would we be able to include information about related reactions? For example, if I looked up the protein for phosphofructokinase (K00850), could it list all the reactions that the protein catalyzes? This would be used for the "related links" part of the metadata

You can create a hyperlink named `related reactions`. Once the user clicks the link, a REST request will be made to list all the related reactions.

**Comment by yosefdroth** [comment]
Thanks! I think all the necessary data is here
