### ISSUE TITLE
Incorporate additional metadata into REST API to display on RNA data pages

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#35]
Endpoint: https://api.datanator.info//rna/halflife/get_info_by_protein_name/?protein_name=Dolichol-P-glucose%20synthetase&_from=0&size=1000

Potential metadata to display
- Gene name (short 3-4 character name)
- Alternative name
- Description of function
- Pathways

UniProt has this metadata for individual genes. Example: https://www.uniprot.org/uniprot/P56757

**Comment by lzy7071** [comment]
Back fill documents where {'gene_name": null}

**Comment by lzy7071** [comment]
Documents with subdocuments that have "ordered_locus_name" do not have gene_name (uniprot collection). Use "function" field

**Comment by lzy7071** [comment]
Can meta fields be a link that makes API requests to relevant indicies/collections?

**Comment by lzy7071** [comment]
[/rna/halflife/get_info_by_protein_name/?](http://api.datanator.info/rna/halflife/get_info_by_protein_name/?protein_name=Protein%20translocase%20subunit%20SecD&_from=0&size=10&taxon_distance=true&species=homo%20sapiens) now returns object containing field name `kegg_meta`
