### ISSUE TITLE
Add taxonomic distance information to RNA half life endpoint to enable taxonomic filtering

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#36]
https://api.datanator.info//rna/halflife/get_info_by_protein_name/?protein_name=Dolichol-P-glucose%20synthetase&_from=0&size=1000

**Comment by lzy7071** [comment]
See [comment](https://github.com/KarrLab/datanator_rest_api/issues/37#issuecomment-589795447) for #37

**Comment by lzy7071** [comment]
See [#37 ](https://github.com/KarrLab/datanator_rest_api/issues/37#issuecomment-594917114)
