### ISSUE TITLE
Add sequence similarity info to RNA and protein data queries to enable more fine-grained filtering of similarity

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#38]

**Comment by lzy7071** [comment]
Use end point '/proteins/similar_protein/refseq/?uniprot_id={}&identity={}' to get similar proteins.

**Comment by lzy7071** [comment]
See [#37](https://github.com/KarrLab/datanator_rest_api/issues/37#issuecomment-594917114)

**Comment by lzy7071** [comment]
Sequence similarity for protein grouped by kegg orthologs will not be done.

**Comment by lzy7071** [comment]
Getting RNA sequence info into database.

**Comment by jonrkarr** [comment]
Closing because this doesn't make sense as we've discussed.
