### ISSUE TITLE
Debug metabolite concentration queries for some metabolites

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#43]
Examples:
- https://api.datanator.info/metabolites/concentration/?metabolite=Uridine%20diphosphate%20glucose&abstract=true
- https://api.datanator.info/metabolites/concentration/?metabolite=UDP-D-glucose&abstract=true
- https://api.datanator.info/metabolites/concentration/?metabolite=Glucose%201-phosphate&abstract=true

These examples all have the same error
```
{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}
```

**Comment by lzy7071** [comment]
Done.
