### ISSUE TITLE
REST API has 503 errors

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#45]
### Example
https://api.datanator.info/ftx/text_search/?index=taxon_tree&query_message=co&from_=0&size=100&fields=tax_name&_source_includes=tax_name

### Errors
Failed to load resource: the server responded with a status of 503 ()
(index):1 

Access to XMLHttpRequest at 'https://api.datanator.info/ftx/text_search/?index=taxon_tree&query_message=co&from_=0&size=100&fields=tax_name&_source_includes=tax_name' from origin 'https://datanator.info' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by jonrkarr** [comment]
Temporarily, I rolled back the version deployed in Heroku to the last working version (v145)

**Comment by lzy7071** [comment]
Should be fixed now.
