### ISSUE TITLE
Create API in /reactions to return a list of reactions given kegg ortholog number

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_rest_api#46]
> Would we be able to include information about related reactions? For example, if I looked up the protein for phosphofructokinase (K00850), could it list all the reactions that the protein catalyzes? This would be used for the "related links" part of the metadata

You can create a hyperlink named `related reactions`. Once the user clicks the link, a REST request will be made to list all the related reactions.

_Originally posted by @lzy7071 in https://github.com/KarrLab/datanator_rest_api/issues/34#issuecomment-597629973_

**Comment by yosefdroth** [comment]
which url should the frontend use for this?

**Comment by lzy7071** [comment]
> which url should the frontend use for this?

[/proteins/related/related_reactions/?ko={}](http://api.datanator.info/proteins/related/related_reactions/?ko=k03100
)

**Comment by yosefdroth** [comment]
I see that this returns the reaction ID's for each reaction. Would it be able to return the reaction name and the reaction equation as well?

It is okay to seperate the "related links" query from the rest of the metadata, but if all the information can be provided in a single query. Right now, it would take two batches of syncronous calls to fill out the "related links". One to get the list of ids, and then another to get the reaction name and equation for each reaction id. This would load the page more slowly, and make the frontend code more complex. 

Would it be possible to return the reaction name and the reaction equation along with the reaction ids?

**Comment by lzy7071** [comment]
> I see that this returns the reaction ID's for each reaction. Would it be able to return the reaction name and the reaction equation as well?
> 
> It is okay to seperate the "related links" query from the rest of the metadata, but if all the information can be provided in a single query. Right now, it would take two batches of syncronous calls to fill out the "related links". One to get the list of ids, and then another to get the reaction name and equation for each reaction id. This would load the page more slowly, and make the frontend code more complex.
> 
> Would it be possible to return the reaction name and the reaction equation along with the reaction ids?

[/proteins/related/related_reactions/?ko={}](http://api.datanator.info/proteins/related/related_reactions/?ko=k03100) now returns distinct reaction documents with `ec_meta`, `substrates`, and `products` fields.

**Comment by yosefdroth** [comment]
The link is returning an internal server error

**Comment by lzy7071** [comment]
> The link is returning an internal server error

It was using an old version of `datanator_query_python`, should be fine within three minutes.

**Comment by yosefdroth** [comment]
im still geting the same error

**Comment by lzy7071** [comment]
> im still geting the same error

My bad, I misunderstood how Pipfile worked. Check back in ten, should be good by then.

**Comment by yosefdroth** [comment]
Thanks! Its working now. 

I think there is an error in the product name. It lists the name as "reaction_participant.product"

**Comment by lzy7071** [comment]
> Thanks! Its working now.
> 
> I think there is an error in the product name. It lists the name as "reaction_participant.product"

Should be good now.

**Comment by yosefdroth** [comment]
This is working -- thank you!
