### ISSUE TITLE
Certain Reaction Queries Stopped Working

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#47]
Some queries don't work anymore. 

For example, the query for ATP + AMP -> ADP is 
https://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K00850&distance=100&depth=100&anchor=Escherichia coli

This does not seem to be working anymore

**Comment by lzy7071** [comment]
/proteins has endpoints for protein queries. The [link](https://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K00850&distance=100&depth=100&anchor=Escherichia%20coli) you pasted is working.

**Comment by yosefdroth** [comment]
You are right! I pasted the wrong link. 

Here is the link that is not working:
https://api.datanator.info/reactions/kinlaw_by_name/?substrates=ATP,AMP&products=ADP&_from=0&size=1000&bound=tight&taxon_distance=false

**Comment by lzy7071** [comment]
> You are right! I pasted the wrong link.
> 
> Here is the link that is not working:
> https://api.datanator.info/reactions/kinlaw_by_name/?substrates=ATP,AMP&products=ADP&_from=0&size=1000&bound=tight&taxon_distance=false

This [link](https://api.datanator.info/reactions/kinlaw_by_name/?substrates=ATP,AMP&products=ADP&_from=0&size=1000&bound=tight&taxon_distance=false) is also working. I would recommend changing `size` to a more reasonable number to improve performance. However, even with `size` set to 1000, the link is still working on my end.
