### ISSUE TITLE
Remove Unqouted NaN from RNA Queries

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#53]
Sometime the RNA query returns NaN (ex: https://api.datanator.info/rna/halflife/get_info_by_ko/?ko_number=K00001&_from=0&size=10)

This causes an error with the JSON parser. I think the convention is not to have unquoted NaN in the JSON. Can it be replaced with null, or something equivalent?

**Comment by lzy7071** [comment]
I clicked on the link but don't see any problem. Perhaps this was already fixed?

**Comment by yosefdroth** [comment]
There is an unquoted NaN in the JSON. It wont raise an error if you click on the link, but I don't think its valid JSON. It raises an error if you try it in a JSON parser

Here is the part the causes the error.
`[
      {
        "cog": "CR",
        "expression_reads_per_kb_per_mb": 32.61417998,
        "gene_end": 903791,
        "gene_start": 902793,
        "growth_medium": "Luria-Bertani (LB) broth (500 ml) at 30 degree celcius, 250 rpm.",
        "halflife": 341.8320648,
        "ncbi_taxonomy_id": 222523,
        "operon": [
          "TU_902663-903791_F"
        ],
        "ordered_locus_name": "BCE_0877",
        "quantification_method": "Illumina GA-II",
        "reference": [
          {
            "doi": "10.1186/gb-2012-13-4-r30",
            "pubmed_id": "22537947"
          }
        ],
        "species": "Bacillus cereus ATCC 10987",
        "strand": "F",
        "taxon_distance": {
          "Bacillus cereus ATCC 10987": 8,
          "Bacillus cereus ATCC 10987_canon_ancestors": [
            "cellular organisms",
            "Bacteria",
            "Firmicutes",
            "Bacilli",
            "Bacillales",
            "Bacillaceae",
            "Bacillus",
            "Bacillus cereus"
          ],
          "homo sapiens": 8,
          "homo sapiens_canon_ancestors": [
            "cellular organisms",
            "Eukaryota",
            "Metazoa",
            "Chordata",
            "Mammalia",
            "Primates",
            "Hominidae",
            "Homo"
          ]
        },
        "transcriptional_end_sites": NaN,
        "transcriptional_start_sites": 902663,
        "unit": "s"
      }
    ]`

For the time being, I just convert NaN to null, but I think the convention is not to use it.

**Comment by yosefdroth** [comment]
I am not sure, the article you posted seems to say that you just shouldn't use NaN in JSON. 

I am having a similar problem now with protein abundance queries (now that it included the protein modifications) -- e.g. [pyruvate kinase](https://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K00873&distance=40)

This causes website page not to work, because since it has NaN, its gets encoded in REACT as a string rather than a list.

**Comment by jonrkarr** [comment]
JSON doesn't support NaN. No some purposes, `null` can be used instead.

**Comment by lzy7071** [comment]
> JSON doesn't support NaN. For some purposes, `null` can be used instead. In the instance that Yosef posted, `null` could be used instead of `NaN`.

There are too many `NaN` in various collections and fields so I did the serialization and deserialization on the backend.
NaN is now serialized to [null](https://api.datanator.info/rna/halflife/get_info_by_ko/?ko_number=K00001&_from=0&size=10), [null](https://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K00873&distance=40)

**Comment by jonrkarr** [comment]
Great.
