### ISSUE TITLE
Certain Reaction Queries Show Up In Full Text Search but Cause Errors

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#54]
Many of reactions show up in the full text search, but return an error in the kinlaw_by_name query. (https://github.com/KarrLab/datanator_frontend/issues/216)

For example:

Glucose --> Glucose:
https://api.datanator.info/reactions/kinlaw_by_name/?substrates=glucose&products=glucose&_from=0&size=10&bound=loose&taxon_distance=true&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D

Glucose + Na+ → Na+ + Glucose
https://api.datanator.info/reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=Glucose%7CNa%252B&products=Na%252B%7CGlucose

**Comment by lzy7071** [comment]
Fixed
