### ISSUE TITLE
Recommended metabolite concentration datasets

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#55]
Elad Noor (@eladnoor) recommended these datasets. In order of usefulness and easy of use:
- Park et al. 2016 - https://www.nature.com/articles/nchembio.2077 (several species)
  - Supplementary Data Set 2
  - Supplementary Data Set 3
- Gerosa et al. 2015 - http://dx.doi.org/10.1016/j.cels.2015.09.008  (E. coli)
  - Data S1, "Metabolite concentrations"
  - Data S2, "Metabolite concentrations"
- Hackett et al. 2016 - https://science.sciencemag.org/content/354/6311/aaf2786 (S. cerevisiae)
  - Table S9, "Metabolite log2 RA" -- might be hard to interpret because the concentrations are reported in relative units.

Additional datasets
- Dataset S1 of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3188480/#pcbi.1002166.s002
  - This already integrates several papers
- Table 1 of https://aem.asm.org/content/77/22/7984/figures-only
- Page 4A and 5A of http://www.rsc.org/suppdata/mb/c3/c3mb70113a/c3mb70113a.pdf. For 5A, use cell volume = 6.7E-17 L

I think this might be close to all that we'll be able to find. This gives us 5-7 papers to work with, in addition to ECMDB and YMDB.
- I used Microsoft Academic to search for similar papers. I didn't find much. 
- I looked through the citations of a 2009 paper from Josh Rabinowitz, which was one of the first metabolome-wide studies. I didn't find much.
- I looked for reviews by Josh Ribowitz (last author of most of the above papers). I didn't find much.
- I looked through the papers that the above papers cited. This didn't yield much.
- I used Google search, but didn't find much.

**Comment by lzy7071** [comment]
I have moved the issue to KarrLab/datanator since this is a database content issue.

**Comment by jonrkarr** [comment]
Additional papers
- 10.1016/j.jchromb.2011.10.036 (yeast)
   - Table 4
- 10.1021/acs.analchem.6b03731
   - Supplementary Excel file ac6b03731_si_002.xlsx, "Table S4"
