### ISSUE TITLE
Null ID in pH Distribution

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#56]
One of the id's is null in the pH distribution - https://api.datanator.info/reactions/summary/get_frequency/?field=temperature

**Comment by jonrkarr** [comment]
I think this represent the number of measurements for which no pH metadata is available. If you're only visualizing the distribution of the available metadata, this can be ignored.

**Comment by jonrkarr** [comment]
It looks like there are 63,134 total measurements. Of these 5,643 (8.9%) have no pH metadata.

The available pH metadata could be visualized as a histogram or as a kernel density line plot (more sophisticated; basically this is another way to visualize the same information that is not sensitive to the choice of bin size).

This webpage provides JavaScript code for a kernel density line:
https://gist.github.com/mbostock/4341954

**Comment by jonrkarr** [comment]
There's also a NPM package
https://www.npmjs.com/package/kernel-smooth
example: https://github.com/Planeshifter/kernel-smooth/blob/master/examples/index.js

**Comment by yosefdroth** [comment]
Good call -- thanks!

I was planning on making a histogram using charjs -- I will check out the kernel density line you posted.

**Comment by lzy7071** [comment]
Some of the entries in sabiork collection have no `pH` values, indicated by `null` value here.
