### ISSUE TITLE
Reaction shows up in Kegg related reactions but has no data in kinlaw_by_name

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#58]
For: Isocitrate → cis-Aconitate + H2O
This reaction comes up in the [related reactions search for K01681](https://api.datanator.info/proteins/related/related_reactions/?ko=K01681)

However, no data comes up when its searched for in [kinlaw_by_name](https://api.datanator.info/reactions/kinlaw_by_name/?substrates=Isocitrate&products=H2O|cis-Aconitate&_from=0&size=10&bound=loose&taxon_distance=false&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D).

I entered each participant manually into api.datanator.info to check it if was a parsing error, but I still got the same issue.

**Comment by lzy7071** [comment]
Thank you for letting me know. This will be fixed in half an hour. It was due to changes made to `sabio_rk ` collection and the backend function used by `kinlaw_by_name`.

**Comment by yosefdroth** [comment]
Thanks! 

I found a similar problem with:
[H+ → H+](https://api.datanator.info/reactions/kinlaw_by_name/?substrates=H%2B&products=H%2B&_from=0&size=10&bound=tight&taxon_distance=false&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D
)
It comes up in the [full text search](https://api.datanator.info/ftx/text_search/num_of_index/?query_message=H%2B&index=sabio_reaction_entries&from_=0&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzyme_name&fields=product_names&fields=substrate_names&fields=enzymes.subunit.canonical_sequence&fields=species), but has no data in kinlaw_by_name.

**Comment by yosefdroth** [comment]
[H+ + Na+ → H+ + Na+](https://api.datanator.info/reactions/kinlaw_by_name/?substrates=H%2B|Na%2B&products=H%2B|Na%2B&_from=0&size=10&bound=tight&taxon_distance=false&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D) as well

**Comment by lzy7071** [comment]
> [H+ + Na+ → H+ + Na+](https://api.datanator.info/reactions/kinlaw_by_name/?substrates=H%2B%7CNa%2B&products=H%2B%7CNa%2B&_from=0&size=10&bound=tight&taxon_distance=false&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D) as well



> Thanks!
> 
> I found a similar problem with:
> [H+ → H+](https://api.datanator.info/reactions/kinlaw_by_name/?substrates=H%2B&products=H%2B&_from=0&size=10&bound=tight&taxon_distance=false&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D)
> It comes up in the [full text search](https://api.datanator.info/ftx/text_search/num_of_index/?query_message=H%2B&index=sabio_reaction_entries&from_=0&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzyme_name&fields=product_names&fields=substrate_names&fields=enzymes.subunit.canonical_sequence&fields=species), but has no data in kinlaw_by_name.

Same cause.

**Comment by lzy7071** [comment]
Fixed.
