### ISSUE TITLE
Some RNA calls to get_info_by_ko break from schema

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#59]
The schema for get_info_by_ko is:
```
[
  {
    "halflives": [
      {
        "halflife": 0,
        "ncbi_taxonomy_id": 0,
        "reference": [
          {
            "doi": "string"
          }
        ],
        "species": "string",
        "unit": "string"
      }
    ],
    "ko_number": "string",
    "protein_names": [
      "string"
    ],
    "uniprot_id": "string"
  }
]
```

However, for https://api.datanator.info/rna/halflife/get_info_by_ko/?ko_number=K17554&_from=0&size=1000 the schema seems to be different. I think the half-lives are recorded under varying gmXXXXXX values:

"values": [
          {
            "biological_replicates": "a1",
            **"gm07029": 2.6805575873021197,**
            "note": "independent cell cultures for the same cell line",
            "unit": "hr"
          },
          {
            "biological_replicates": "a2",
            **"gm07029": 3.3753493369203564,**
            "note": "independent cell cultures for the same cell line",
            "unit": "hr"
          },

**Comment by lzy7071** [comment]
I moved this issue to karrlab/datanator issue [#43](https://github.com/KarrLab/datanator/issues/43#issue-608420859)
