### ISSUE TITLE
Inchi concentration calls not working for some metabolites

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#63]
e.g. [N(2)-formyl-N(1)-(5-phospho-D-ribosyl)glycinamide](https://api.datanator.info/metabolites/concentrations/?inchikey=VDXLUNDMVKSKHO-ZRTZXPPTSA-N)
[
2,5-Diamino-4-hydroxy-6-(5-phosphoribosylamino)pyrimidine ](https://api.datanator.info/metabolites/concentrations/?inchikey=OCLCLRXKNJCOJD-UMMCILCDSA-L)

**Comment by lzy7071** [comment]
[N(2)-formyl-N(1)-(5-phospho-D-ribosyl)glycinamide](http://www.ymdb.ca/compounds/YMDB00759) or [2,5-Diamino-4-hydroxy-6-(5-phosphoribosylamino)pyrimidine](http://www.ymdb.ca/compounds/YMDB00147) does not have concentration information, response returned as null.

**Comment by yosefdroth** [comment]
At least for me, the backend does not return an error -- it does not return anything. Are you getting the same thing? 

If so, I think the best thing is to have the backend return an error message, or an empty set.

**Comment by lzy7071** [comment]
> At least for me, the backend does not return an error -- it does not return anything. Are you getting the same thing?

Weird. I thought it would be a NoneType. It'll  now return an empty list.
