### ISSUE TITLE
Additional Data Returned in /metabolites/concentrations/?inchikey=

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#64]
Thanks for the new backend call! I have it working in the update_metab branch. 

Would you be able to add data from these fields:

 - growth_phase
 - growth_media
 - database_id (if applicable - e.g. the ymdb_id or the m2m_id)
 - strain (if applicable)

Some of this data is present in the initial ecmdb/ymdb collection.

**Comment by lzy7071** [comment]
Use `/metabolites/meta/?inchikey=` to retrieve meta information (database_id)
`growth_phase`, `growth_media`, and `strain` information, if present, is contained within objects in `concentrations` array, e.g. [ACFIXJIJDZMPPO-NCHANQSKSA-N](http://api.datanator.info/metabolites/concentrations/?inchikey=ACFIXJIJDZMPPO-NCHANQSKSA-N)

**Comment by yosefdroth** [comment]
You are correct, I see that growth_media and strain is there.

However, it appears to be missing growth_system and growth_status. Compare the two calls for ATP:
[inchi](https://api.datanator.info/metabolites/concentrations/?inchikey=ZKHQWZAMYRWXGA-KQYNXXCUSA-N)
[Name](https://api.datanator.info/metabolites/concentration/?species=Escherichia%20coli&metabolite=ATP) (the old call)

For the concentration value that is 8980.0:
The old call call has:
`"concentration": [
          "310.0",
          "9640.0",
          "8980.0",
          "4140.0",
          "1310.0",
          "4150.0"
        ],
        "concentration_units": [
          "uM",
          "uM",
          "uM",
          "uM",
          "uM",
          "uM"
        ],
        "error": [
          "12.0",
          "0.0",
          "0.0",
          "0.0",
          "0.0",
          "2850.0"
        ],
        "growth_media": [
          "0.2 g/L NH4Cl, 2.0 g/L (NH4)2SO4, 3.25 g/L KH2PO4, 2.5 g/L K2HPO4, 1.5 g/L NaH2PO4, 0.5 g/L MgSO4; trace substances: 10 mg/L CaCl2, 0.5 mg/L ZnSO4, 0.25 mg/L CuCl2, 0.25 mg/L  MnSO4, 0.175 mg/L CoCl2, 0.125 mg/L H3BO3, 2.5 mg/L AlCl3, 0.5 mg/L Na2MoO4, 10",
          "Gutnick minimal complete medium (4.7 g/L KH2PO4; 13.5 g/L K2HPO4; 1 g/L K2SO4; 0.1 g/L MgSO4-7H2O; 10 mM NH4Cl) with 4 g/L glucose",
          "Gutnick minimal complete medium (4.7 g/L KH2PO4; 13.5 g/L K2HPO4; 1 g/L K2SO4; 0.1 g/L MgSO4-7H2O; 10 mM NH4Cl) with 4 g/L glycerol",
          "Gutnick minimal complete medium (4.7 g/L KH2PO4; 13.5 g/L K2HPO4; 1 g/L K2SO4; 0.1 g/L MgSO4-7H2O; 10 mM NH4Cl) with 4 g/L acetate",
          "48 mM Na2HPO4, 22 mM KH2PO4, 10 mM NaCl, 45 mM (NH4)2SO4, supplemented with 1 mM MgSO4, 1 mg/l thiamine\u00b7HCl, 5.6 mg/l CaCl2, 8 mg/l FeCl3, 1 mg/l MnCl2\u00b74H2O, 1.7 mg/l ZnCl2, 0.43 mg/l CuCl2\u00b72H2O, 0.6 mg/l CoCl2\u00b72H2O and 0.6 mg/l Na2MoO4\u00b72H2O.  4 g/L Gluco",
          null
        ],
        "growth_status": [
          "Stationary Phase, glucose limited",
          "Mid-Log Phase",
          "Mid-Log Phase",
          "Mid-Log Phase",
          "Stationary Phase, glucose limited",
          null
        ],
        "growth_system": [
          "Bioreactor, pH controlled, aerated, dilution rate=0.125 L/h",
          "Shake flask and filter culture",
          "Shake flask and filter culture",
          "Shake flask and filter culture",
          "Bioreactor, pH controlled, O2 and CO2 controlled, dilution rate: 0.2/h",
          null
        ]`

which includes growth_system and growth_status.

But the inchi call has:`{
      "concentration": "8980.0",
      "error": "0.0",
      "growth_meda": "Gutnick minimal complete medium (4.7 g/L KH2PO4; 13.5 g/L K2HPO4; 1 g/L K2SO4; 0.1 g/L MgSO4-7H2O; 10 mM NH4Cl) with 4 g/L glycerol",
      "internal": null,
      "ncbi_taxonomy_id": 562,
      "reference": {
        "pubmed_id": "19561621",
        "reference_text": "Bennett, B. D., Kimball, E. H., Gao, M., Osterhout, R., Van Dien, S. J., Rabinowitz, J. D. (2009). \"Absolute metabolite concentrations and implied enzyme active site occupancy in Escherichia coli.\" Nat Chem Biol 5:593-599."
      },
      "species_name": "Escherichia coli",
      "strain": "K12 NCM3722",
      "unit": "uM"
    }`

Also, there is a typo -- can you change growth_meda to growth_media?

**Comment by lzy7071** [comment]
This has been fixed.

**Comment by yosefdroth** [comment]
Can you please add the source ID to the concentration calls? This was the m2m_id and ymdb_id that was used to link back to those websites. 

Right now, I am using metabolites/concentrations/similar_compounds, so it only really need to be returned in that call.

**Comment by lzy7071** [comment]
> Can you please add the source ID to the concentration calls? This was the m2m_id and ymdb_id that was used to link back to those websites.
> 
> Right now, I am using metabolites/concentrations/similar_compounds, so it only really need to be returned in that call.

The metadata information can be acquired from the `/metabolites/meta/?inchikey={}` API call. To get the information directly from the metabolite-specific page, one can use the meta endpoint since inchikey is present in `concentration` document.

**Comment by yosefdroth** [comment]
The metadata does not have the information for all the related metabolites, only for the metabolite which is queried. For example, if someone goes to the ATP page, the metadata call is only for ATP, but the concentration table also shows data from ADP.

In theory, I could do an API call for each related compound. However, this would slow down the loading of the page because it would have to be a synchronous call (because the frontend doesn't know the identity of the related compounds until after the concentration call is returned). This would also make the frontend code a bit more complex because it would require making many additional API calls, and have to wair for them all to be completed. 

Would it be possible to add the source ID directly into the metabolites/concentrations/similar_compounds? 

This would mean that the only two calls that have to be made are 
1) /metabolites/meta/?inchikey={}
2) metabolites/concentrations/similar_compounds
And then no API calls would have to be synchronous

**Comment by lzy7071** [comment]
> The metadata does not have the information for all the related metabolites, only for the metabolite which is queried. For example, if someone goes to the ATP page, the metadata call is only for ATP, but the concentration table also shows data from ADP.
> 
> In theory, I could do an API call for each related compound. However, this would slow down the loading of the page because it would have to be a synchronous call (because the frontend doesn't know the identity of the related compounds until after the concentration call is returned). This would also make the frontend code a bit more complex because it would require making many additional API calls, and have to wair for them all to be completed.
> 
> Would it be possible to add the source ID directly into the metabolites/concentrations/similar_compounds?
> 
> This would mean that the only two calls that have to be made are
> 
> 1. /metabolites/meta/?inchikey={}
> 2. metabolites/concentrations/similar_compounds
>    And then no API calls would have to be synchronous

I see what you meant now. 
As we have expanded our metabolites concentration data beyond the scope of ECMDB and YMDB, I do not agree that we need a pointer back towards ECMDB or YMDB as we cannot assume each similar metabolite can be found in the said database. If it is the concentration observation sources that you want to show, the primary sources with DOI or pubmedid are included in each `concentration` object.
However, if you are interested in pointing the user toward a more specific meta page for the similar compound, you can use the chebi ID contained in each `concentrations` document and point link to [https://www.ebi.ac.uk/chebi/searchId.do?chebiId={}](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:30831). Or if you prefer some other identifier, you can lazy load the `/metabolites/meta/` endpoint and parse out the identifier when the user clicks on the link.

**Comment by jonrkarr** [comment]
The source info is incorporated now. I believe this issue has been addressed.
