### ISSUE TITLE
Write endpoint to retrieve RNA modification data

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_rest_api#66]
`rna_modification` collection. (Protein modification information is already in `uniprot` collection)

**Comment by lzy7071** [comment]
It requires user intent because data available are on tRNA or rRNA that cannot be cross-referenced with uniprot meta information.
GeneSearchResultList.js on datanator_frontend needs to make two API calls simultaneously and check match score from rna_modification index.

**Comment by jonrkarr** [comment]
@lzy7071 what's the REST endpoint for the RNA modification collection? Can you post an example?

**Comment by lzy7071** [comment]
> @lzy7071 what's the REST endpoint for the RNA modification collection? Can you post an example?

I just opened `rna_modification` index for ftx searches. An example link: [http://api.datanator.info/ftx/text_search/num_of_index/?query_message=Aminoacyl-tRNA%20biosynthesis&index=rna_modification&from_=0&size=10&fields=definition&fields=kegg_pathway_name](http://api.datanator.info/ftx/text_search/num_of_index/?query_message=Aminoacyl-tRNA%20biosynthesis&index=rna_modification&from_=0&size=10&fields=definition&fields=kegg_pathway_name). Of course, `fields` can be adjusted.
The issue is that I am not sure how to guage user intent and display such information on the intermediate page or on gene-specific page.

**Comment by jonrkarr** [comment]
I thought rRNA and tRNA could be treated the same as other genes because there are KEGG ortholog groups for rRNA and tRNA.
- The search results page would display rRNA and tRNA ortholog groups that match queries. 
- The gene page for an rRNA or tRNA would display RNA modifications for an ortholog group. This would be retrieved using the id for the KEGG ortholog group. The other data tables wouldn't be displayed; in place of the RNA half-life table the page would say "No data is available." The React code could recognize that the ortholog group represents non-coding RNA and omit the protein data tables entirely.

**Comment by lzy7071** [comment]
> I thought rRNA and tRNA could be treated the same as other genes because there are KEGG ortholog groups for rRNA and tRNA.
> - The search results page would display rRNA and tRNA ortholog groups that match queries. 
> - The gene page for an rRNA or tRNA would display RNA modifications for an ortholog group. This would be retrieved using the id for the KEGG ortholog group. The other data tables wouldn't be displayed; in place of the RNA half-life table the page would say "No data is available." The React code could recognize that the ortholog group represents non-coding RNA and omit the protein data tables entirely.

You are right! I completely forgot about that for some reason. I'll implement it tomorrow.

**Comment by lzy7071** [comment]
Endpoint for retrieving RNA modification information by kegg: [http://api.datanator.info/rna/modification/get_modifications_by_ko/?ko_number={}&_from=0&size=10
](http://api.datanator.info/rna/modification/get_modifications_by_ko/?ko_number=K14218&_from=0&size=10
)

**Comment by jonrkarr** [comment]
Can you add taxonomic distance calculations to this endpoint?

**Comment by lzy7071** [comment]
> Can you add taxonomic distance calculations to this endpoint?

The endpoint is now up [https://api.datanator.info/rna/modification/get_modifications_by_ko/?ko_number=K14236&_from=0&size=10&target_organism=Escherichia%20coli&taxon_distance=true](https://api.datanator.info/rna/modification/get_modifications_by_ko/?ko_number=K14236&_from=0&size=10&target_organism=Escherichia%20coli&taxon_distance=true)
I still haven't gotten around to this issue https://github.com/KarrLab/datanator_query_python/issues/11#issue-622687792 yet.
