### ISSUE TITLE
add metabolite name to metabolites/concentrations/similar_compounds/

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#67]
See the [ATP query](https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=ZKHQWZAMYRWXGA-KQYNXXCUSA-N) for similar compounds. Would you be able to also return the compound name for each compound?

I think the best way to add the name would be to repeat the schema in metabolites/concentrations/ -- which is to add a field "metabolite" to each object, and having the value be the name.

**Comment by lzy7071** [comment]
Done.
