### ISSUE TITLE
Return information about the taxon/source associated with the metabolite localizations

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#69]
This issue is in response to feedback from @YinHoon .

This query returns information about the localization of each metabolite:
https://api.datanator.info/metabolites/meta/?inchikey=HSCJRCZFDFQWRP-LPTOLDDLSA-N
```
{
  ...
  cellular_locations: {
    cellular_location: ["cytoplasm", ...]
  }
  ...
}
```

The query provides localization information merged from both ECMDB and YMDB about E. coli and yeast.

We should indicate to users which localizations correspond to E. coli, and which correspond to year.

To communicate this information to users, the endpoint needs to return the source of each localization such as below (the output doesn't need to follow this exact format; the important thing is to transmit the source (ECMB, YMDB) and/or taxon (E. coli, yeast) associated with each localization). Once this is updated, we'll also need to update `datanator_frontend/src/scences/BiochemicalEntityDetails/Metabolite/MetadataSection.js:formatMetadata` L305-317.
```
{
  ...
  cellular_locations: {
    cellular_location: [
      {"source": "ECMDB", "taxon", "Escherichia coli", "name": "cytoplasm"},
      {"source": "YMDB", "taxon", "Saccharomyces cerevisiae", "name": "cytoplasm"},
      ...
    ]
  }
  ...
}
```

**Comment by lzy7071** [comment]
I have changed the `cellular_locations` to follows:
{
  ...
  cellular_locations: [
    {"cellular_location": (str) "cytoplasm",
     "references": (list) ["ECMDB"]
    },
    ...
  ]
}
```

**Comment by jonrkarr** [comment]
Thanks. I integrated this into the frontend.
