### ISSUE TITLE
Add taxonomic similarity to /metabolites/concentrations/similar_compounds/

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#71]

**Comment by lzy7071** [comment]
Temporarily using iteration to create `taxon_distance` object.
[/metabolites/concentrations/similar_compounds/](https://datanator.api/metabolites/concentrations/similar_compounds/?inchikey=BOPGDPNILDQYTO-NNYOXOHSSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=true) now has the option to turn on taxon_distance object

**Comment by lzy7071** [comment]
Endpoint `/metabolites/concentrations/similar_compounds/? `[http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=NBSCHQHZLSJFNQ-GASJEMHNSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=false](http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=NBSCHQHZLSJFNQ-GASJEMHNSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=false)
now contains concentration information on the metabolite itself. Taxon distance information can be toggled on / off.

**Comment by lzy7071** [comment]
Need to transition taxon_distance calculation to `aggregation`

**Comment by lzy7071** [comment]
Closed because #70 covers the improvement.
