### ISSUE TITLE
Add InchiKey information for Cofactors

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#72]
In the /reactions/kinlaw_by_name/, the query returns cofactor information. The frontend used this to link to the corresponding metabolite page. Now that we switched the querying to inchi for metabolite pages, the frontend needs to know the inchikey of the cofactors. 

Can you please add InchiKey information to the cofactors in /reactions/kinlaw_by_name/?

**Comment by lzy7071** [comment]
I don't think this is possible, or at the least, trivial, to identify inchikey for cofactors. For example, [EC: 1.1.1.1](https://enzyme.expasy.org/EC/1.1.1.1) has a cofactor described as "Zn(2+) or Fe cation" in the expasy database, from which our EC meta information was parsed. ExPASy does not have inchikey information for cofactors.
I think it would be more appropriate to use full-text search, if we are so inclined to link cofactors to our own database (`metabolites_meta`), given the cofactor can be a description as mentioned. Example: [http://api.datanator.info/ftx/text_search/num_of_index/?query_message=Zn%282%2B%29%20or%20Fe%20cation&index=metabolites_meta&from_=0&size=5&fields=synonyms&fields=name](http://api.datanator.info/ftx/text_search/num_of_index/?query_message=Zn%282%2B%29%20or%20Fe%20cation&index=metabolites_meta&from_=0&size=5&fields=synonyms&fields=name
)

**Comment by lzy7071** [comment]
Closing this issue as discussed over weekly meeting ().
