### ISSUE TITLE
Metabolite concentrations now seem to be repeated many times. Is this correct?

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#73]
Example:
https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=HSCJRCZFDFQWRP-RDKQLNKOSA-N&threshold=0.6&taxon_distance=false

This can also be seen in the `update_metab` branch of the frontend.
http://localhost:3000/metabolite/HSCJRCZFDFQWRP-RDKQLNKOSA-N

Each measurement appears to be repeated many times in association with multiple Kms and EC numbers. I think this might be a misinterpretation of the concentration.

**Comment by lzy7071** [comment]
Here are the two supplementary tables I used for parsing the information: [1](https://1drv.ms/x/s!AqvIIIEFGr2PhZYyLLtOI_M9ZCwRGg?e=egI73Y), [2](https://1drv.ms/x/s!AqvIIIEFGr2PhZYzSY6NaIxJRh-_KA?e=gkIfOB).
It was trying to show absolute concentrations to enzyme binding affinities. I didn't realize the absolute concentration values are all the same regardless of the enzyme. I will fix it on the database side.

**Comment by jonrkarr** [comment]
Thanks. On the query side, it looks like the concentrations have been joined (in the SQL sense) to all of the associated kinetic parameters. That might be a good way to display kinetic parameters, but I think the rows should be grouped for display as measurements of metabolite concentrations.

**Comment by lzy7071** [comment]
The concentration schema for data from `"doi": "10.1038/nchembio.2077"` has been changed:
https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=HSCJRCZFDFQWRP-RDKQLNKOSA-N&threshold=0.6&taxon_distance=false

**Comment by lzy7071** [comment]
> . That might be a good way to display kinetic parameters, but I think the rows should be grouped for display as measurements of metabolite

I finished modifying and commenting 3 seconds after your post, lol. See above comment https://github.com/KarrLab/datanator_rest_api/issues/73#issuecomment-631782948

**Comment by jonrkarr** [comment]
Thanks!

**Comment by lzy7071** [comment]
Closing issue because it is resolved.
