### ISSUE TITLE
Some metabolite concentrations lack units

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#76]
Example: entry with concentration 0.00839586454902474 in 
https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=RFSUNEUAIZKAJO-ARQDHWQXSA-N&threshold=0.6&taxon_distance=false

**Comment by lzy7071** [comment]
> Example: entry with concentration 0.00839586454902474 in
> https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=RFSUNEUAIZKAJO-ARQDHWQXSA-N&threshold=0.6&taxon_distance=false

I placed the unit information in each `affinity` object but forgot to include it outside of the `affinities` object. I will refill that information but in the meantime, one can use the unit inside `affinity` obeject.

**Comment by lzy7071** [comment]
fixed.
