### ISSUE TITLE
Integrate rRNA and tRNA ortholog groups into the full text search for ko groups

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#81]
For example, the search currently returns no results for K14236 (tRNA-Tyr), even though we have modification data for this ortholog group.

https://api.datanator.info/ftx/text_search/num_of_index/?query_message=K14236&index=sabio_reaction_entries&from_=0&size=10&fields=enzyme_names&fields=ec-code&fields=substrates&fields=substrate_names&fields=products&fields=product_names

**Comment by lzy7071** [comment]
The indices for full text is also adjustable. The endpoint to use is `/ftx/text_search/indices_in_page/?`
[http://api.datanator.info/ftx/text_search/indices_in_page/?query_message=K14236&index=sabio_reaction_entries%2Crna_modification&iof=sabio_reaction_entries&iof=rna_modification&from_=0&size=10&fields=kegg_orthology_id&fields=enzyme_names&fields=ec-code&fields=substrates&fields=substrate_names&fields=products&fields=product_names](http://api.datanator.info/ftx/text_search/indices_in_page/?query_message=K14236&index=sabio_reaction_entries%2Crna_modification&iof=sabio_reaction_entries&iof=rna_modification&from_=0&size=10&fields=kegg_orthology_id&fields=enzyme_names&fields=ec-code&fields=substrates&fields=substrate_names&fields=products&fields=product_names)

**Comment by jonrkarr** [comment]
My first post was misleading. The gene search currently uses this endpoint:
https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=K14236&from_=0&size=10&fields=ko_name&fields=ko_number&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number

This seems to only searches over proteins. How should I change this to also search over non-coding RNA?

**Comment by lzy7071** [comment]
> My first post was misleading. The gene search currently uses this endpoint:
> https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=K14236&from_=0&size=10&fields=ko_name&fields=ko_number&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number
> 
> This seems to only searches over proteins. How should I change this to also search over non-coding RNA?

Ah, I see. I'll change it on the backend because there was a lot of settings in the Elasticsearch aggregation step.

**Comment by jonrkarr** [comment]
Thanks!

**Comment by lzy7071** [comment]
The link works now [https://api.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=K14236&from_=0&size=10&fields=ko_name&fields=ko_number&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number](https://api.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=K14236&from_=0&size=10&fields=ko_name&fields=ko_number&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number)

The issue has been addressed with https://github.com/KarrLab/datanator_rest_api/commit/371ccb0dde25cfdd5c876c45e53f82cbc5965844. I also renamed the endpoint from `/ftx/text_search/protein_ranked_by_ko/` to `/ftx/text_search/gene_ranked_by_ko/`. The change has been applied to frontend https://github.com/KarrLab/datanator_frontend/commit/69fcbe5d99b106016f36c15bf64f9e18d26c8999

**Comment by jonrkarr** [comment]
The frontend now works with the new endpoint.

For non-coding RNA, the top ko doesn't include the name of the ortholog group. Can you add the names?

Currently the KO groups are displayed like this:
> **K14236**
> KEGG: K14236

Rather than
> **tRNA Tyr**
> KEGG: K14236

**Comment by lzy7071** [comment]
> The frontend now works with the new endpoint.
> 
> For non-coding RNA, the top ko doesn't include the name of the ortholog group. Can you add the names?
> 
> Currently the KO groups are displayed like this:
> > **K14236**
> > KEGG: K14236
> 
> Rather than
> > **tRNA Tyr**
> > KEGG: K14236

Done. There's now a `definition` field.

**Comment by jonrkarr** [comment]
This is integrated into the frontend.
