### ISSUE TITLE
Some metabolite concentration queries with organisms have 500 errors

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#87]
Examples:
- https://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=AAAFZMYJJHWUPN-TXICZTDVSA-N&threshold=0.6&target_species=Colius%20colius&taxon_distance=true
- YXJDFQJKERBOBM-TXICZTDVSA-N
- KTVPXOYAKDPRHY-AIHAYLRMSA-N

**Comment by lzy7071** [comment]
Fixed.
