### ISSUE TITLE
testapi.datanator.info is down

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#94]
Example:
https://testapi.datanator.info/proteins/precise_abundance/?uniprot_id=Q54JE4&taget_species=homo%20sapiens&taxon_distance=true

**Comment by lzy7071** [comment]
> Example:
> https://testapi.datanator.info/proteins/precise_abundance/?uniprot_id=Q54JE4&taget_species=homo%20sapiens&taxon_distance=true

Somehow the webdyno on Heroku was turned off. It's fixed now.
