### ISSUE TITLE
/proteins/proximity_abundance/proximity_abundance_kegg/ is not working

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_rest_api#95]
e.g. the query for pyruvate kinase (KO number K00873):
https://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K00873&distance=40

**Comment by lzy7071** [comment]
This is related to https://github.com/KarrLab/datanator/issues/52#issue-624500620. The link above should be working via a temporary solution now.
