### ISSUE TITLE
Extend related reactions (to a KO group) endpoint to individual UniProt ids

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#96]
We need 1 more endpoint to provide all of the content for gene pages that are identified via a UniProt id.

Two options
- (Preferred) 1 add an endpoint to search reactions by UniProt id. The endpoint needs to return the same information as the `/proteins/related/related_reactions/` endpoint.
  - Reaction names
  - Subsrate ids (InChiKey or hash of name)
  - Substrate names
  - Product ids (InChiKey or hash of name)
  - Product names
  - EC numbers, if available
- Add an optional UniProt id argument to `/proteins/related/related_reactions/` and make the `ko` argument optional (individually, the arguments would be optional; together, one argument would be required).

**Comment by lzy7071** [comment]
I took the preferred route. 

- `/proteins/related/related_reactions/` was renamed to `/proteins/related/related_reactions_by_ko/`

- A new endpoint `/proteins/related/related_reactions_by_uniprot/` was created.

**Comment by jonrkarr** [comment]
I integrated this into the frontend
