### ISSUE TITLE
Add endpoint that returns the taxonomic distribution of the Datanator

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#97]
We need another endpoint to add a chart of the taxonomic distribution of Datanator to the stats page. See also KarrLab/datanator_frontend/#256.

Endpoint:
- Return the number of observations of each organism for the most frequently observed organisms.
- The results can be paginated. We only need ~10 most frequent organisms for the chart.
- Also return the total number of observations so that the number of observations for all other organisms can be calculated

**Comment by lzy7071** [comment]
This has turned out to be a lot more complicated than I expected. The endpoint is finally up https://testapi.datanator.info/taxon/summary/taxon_distribution. I stored the distribution object here: https://github.com/KarrLab/datanator_query_python/blob/testapi/docs/taxon_distribution_frontend.json

**Comment by jonrkarr** [comment]
I integrated this into the frontend
